$(document).ready(function() {
        $("header").remove();
        $("footer").remove();
        $("<link rel='icon' href="+window.location.origin+"/wp-content/plugins/mmrs/img_logo/favicon-32x32.png type='image/png' sizes='32x32'>").prependTo("head");
        var insert = "<div class='entete-mmrs'><img src="+window.location.origin+"/wp-content/plugins/mmrs/img_logo/mmrs.png class='logo-mmrs logo'>";
            insert += "<h1 class='texte_slide'>Ministère des Mines et des Ressources Stratégiques</h1>";
            insert += "<img src="+window.location.origin+"/wp-content/plugins/mmrs/img_logo/republic.png class='logo-republic logo'></div>";
            insert +="<nav class='menu-mmrs-nav'><p>test</p></nav>";
        $(insert).insertBefore("#id-menu-mmrs");
        $("#id-menu-mmrs").prependTo(".menu-mmrs-nav");

var slideshow = "<div id='jssor_1' style='position:relative;margin:0 auto;top:0px;left:0px;width:980px;height:380px;overflow:hidden;visibility:hidden;'>";
        slideshow += "<div data-u='loading' class='jssorl-004-double-tail-spin' style='position:absolute;top:0px;left:0px;width:100%;height:100%;text-align:center;background-color:rgba(0,0,0,0.7);'>";
            slideshow += "<img style='margin-top:-19px;position:relative;top:50%;width:38px;height:38px;' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/double-tail-spin.svg />";
        slideshow += "</div>";
        slideshow += "<div data-u='slides' style='cursor:default;position:relative;top:0px;left:0px;width:980px;height:380px;overflow:hidden;'>";
            slideshow += "<div data-fillmode='0' data-idle='2000'>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide1.jpg/>";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide2.jpg/>";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide3.png />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide4.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide5.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide6.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide7.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide8.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide9.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide10.png />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide11.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide12.jpg />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide13.png />";
            slideshow += "</div>";
            slideshow += "<div>";
                slideshow += "<img data-u='image' src="+window.location.origin+"/wp-content/plugins/mmrs/slide_enjana/img/slide14.jpg />";
            slideshow += "</div>";
        slideshow += "</div>";
        slideshow += "<div data-u='navigator' class='jssorb031' style='position:absolute;bottom:16px;right:16px;' data-autocenter='1' data-scale='0.5' data-scale-bottom='0.75'>";
            slideshow += "<div data-u='prototype' class='i' style='width:13px;height:13px;'>";
                slideshow += "<svg viewbox='0 0 16000 16000' style='position:absolute;top:0;left:0;width:100%;height:100%;'>";
                    slideshow += "<circle class='b' cx='8000' cy='8000' r='5800'></circle>";
                slideshow += "</svg>";
            slideshow += "</div>";
        slideshow += "</div>";
    slideshow += "</div>";
    slideshow +="<script type='text/javascript'>jssor_1_slider_init();</script>"
    $(".mon_header").append(slideshow);
});